### ISSUE TITLE
scenario on db failure

### ISSUE THREAD

**Issue by seanyinx** [ServiceComb/ServiceComb-Saga#17]
what to do with db failure in middle of transactions?
compensate or retry?

**Comment by MabinGo** [comment]
Maybe  it's better to do retrying all the time until the database is recovered, cause all the event is store in db.what's your opinion?

**Comment by seanyinx** [comment]
there seems no better way than keep retrying till database is recovered, if some transactions in the request have already started.

if none of the transactions is started, we can safely reject the request.
